stages:
  - test_unit_job

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'
before_script:
- cd reddit
- bundle install

test_unit_job:
 stage: test
 services:
 - mongo:latest
 script:
 - ruby simpletest.rb