stages:
  - test
  - review

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
before_script:
  - cd reddit
  - bundle install

test_unit_job:
  stage: test
  services:
  - mongo:latest
  script:
  - ruby simpletest.rb

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com