---
- name: packer db playbook
  hosts: all
  tasks:
    - name: Download mongo from ya ftp
      get_url:
        url: "{{ item }}"
        dest: /home/ubuntu
      with_items:
        - https://mirror.yandex.ru/mirrors/repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org_4.2.20_amd64.deb
        - https://mirror.yandex.ru/mirrors/repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-tools_4.2.20_amd64.deb
        - https://mirror.yandex.ru/mirrors/repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-shell_4.2.20_amd64.deb
        - https://mirror.yandex.ru/mirrors/repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.20_amd64.deb
        - https://mirror.yandex.ru/mirrors/repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-mongos_4.2.20_amd64.deb

    - wait_for:
        timeout: 15

    - name: install mongodb
      become: true
      shell: "apt-get install /home/ubuntu/mongodb-org*.deb -y"
      register: apt

    - debug:
        var: apt
