---
- wait_for: # need wait before install (apt lock file error issue)
    timeout: 5
  tags: install

- name: install packages
  apt:
    name:
      - git
      - ruby-full
      - ruby-bundler
      - build-essential
    state: present
    update_cache: true
  tags: install
