---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 62.84.114.60
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: Add unit file for reddit
      become: true
      copy:
        src: files/reddit.service
        dest: /etc/systemd/system/reddit.service
      tags: app-tag
      notify: reload reddit

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag
      notify: reload reddit

    - name: enable reddit
      become: true
      systemd:
        name: reddit
        enabled: true
      tags: app-tag

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      tags: deploy-tag
      notify: reload reddit
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags: deploy-tag



  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
    - name: reload reddit
      become: true
      systemd: name=reddit state=restarted
