---
- name: Configure App
  hosts: app
  become: true
  vars:
   db_host: 51.250.14.14
  tasks:
    - name: Add unit file for reddit
      copy:
        src: files/reddit.service
        dest: /etc/systemd/system/reddit.service
      notify: reload reddit

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable reddit
      systemd: name=reddit enabled=yes

  handlers:
  - name: reload reddit
    systemd: name=reddit state=restarted
