---
- name: packer app playbook
  hosts: all
  become: true
  tasks:
    - wait_for:
        timeout: 15
    - name: install packages
      package:
        name:
          - git
          - ruby-full
          - ruby-bundler
          - build-essential
        state: latest
